config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :reviews
  resources :groups
  resources :clubs do
    member do
      get :join
    end
  end
  root 'home#index'
  resources :announcements

  resources :'events' do
    resources :'attendences' do
      collection do
        get :unattend
        get :attend
      end
    end
  end

  namespace :admin do
    resources :reviews
    resources :clubs

    root 'home#index'
    resources :announcements

    resources :'events' do
      resources :'attendences'
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :announcements
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :admin
end

app/models/apply_form.rb
class ApplyForm < ActiveRecord::Base
  belongs_to :user
  belongs_to :offer

  	has_attached_file :CV
	validates_attachment_presence :CV
	validates_attachment_content_type :CV, :content_type => [ 'application/pdf','text/plain']
end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/calculator.rb
class Calculator
  def sum(x,y)
    x + y
  end
end

app/models/club.rb
class Club < ActiveRecord::Base
  mount_uploader :logo, ImageUploader
  has_many :club_users
  has_many :users, through: :club_users
end

app/models/club_user.rb
class ClubUser < ActiveRecord::Base
  belongs_to :club
  belongs_to :user

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendences
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :reviews
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	has_many :apply_forms

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :clubs
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
before_filter :find_event, only: [:show,:update,:edit,:destroy]

  def index
    @events=Event.all
  end

  def new
    @event=Event.new
  end

  def create
    @event=Event.new(events_params)
    if @event.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show

  end

  def update

  end

  def destroy

  end

  def edit

  end

  private
    def events_params
      params.require(:event).permit(:title,:description,:start_at,:end_at)
    end

    def find_event
      @event=Event.find(params[:id])
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy, :join]

  # GET /clubs
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  def show
  end

  def join
    @club.club_users.build(user_id: current_user.id, status: 'pending')
    if @club.save
      redirect_to @club, notice: 'Request was sent successfully.'
    else
      render :index
    end
  end

  # GET /clubs/new

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def club_params
      params.require(:club).permit(:name, :description, :logo)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :find_event, only: [:show]

  def index
    @events=Event.all
  end

  def show
    @attendences=Attendence.where(event_id: @event.id)
    @attendence= :find_attendence
  end

  private

  def find_event
    @event=Event.find(params[:id])
  end

  def find_attendence
    @attendence=Attendence.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events=Event.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apply_forms_helper.rb
module ApplyFormsHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/events/_form.html.haml
=simple_form_for([:admin,@event]) do |f|
  =f.input :title
  =f.input :description
  =f.input :start_at
  =f.input :end_at

  =f.button :submit

app/views/admin/events/index.html.haml
%h1 hallo in admin events
-@events.each do |event|
  =event.title
  =event.description
= link_to 'New event', new_admin_event_path

app/views/admin/events/new.html.haml
=render 'form'

app/views/events/index.html.haml
-@events.each do |event|
  %p=event.title
  %p=event.description
  %p=link_to t('show'), event

app/views/events/show.html.haml
.container-fluid
  .col-lg-6
    .panel
      .panel-heading
        .panel-body
          %h1=@event.title
          %p=@event.description
          %p=@event.start_at
          %p=@event.end_at
          %p=link_to 'back', root_path
  .col-lg-3
    .panel
      .panel-heading
        .panel-body
          %h4 Attendance list:
          -@attendences.each do |event|
            =event.user.email
            =event.created_at
          - if user_signed_in?
            -if @attendences.where(user_id: current_user.id).count > 0
              %br You already have attendence to this event
              = link_to 'Unattend', unattend_event_attendences_path(@event), class: "btn btn-danger"
            -else
              = link_to 'Attend', attend_event_attendences_path(@event), class: "btn btn-success"
          - else
            %p Log In to attend this event
            = link_to 'Log In', new_user_session_path